global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5000']
    metrics_path: /metrics

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5001']
    metrics_path: /metrics

  - job_name: 'shopping-cart-service'
    static_configs:
      - targets: ['shopping-cart-service:5002']
    metrics_path: /metrics

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5003']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:5004']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:5005']
    metrics_path: /metrics
